name: Node.js CI

on:
  push:
    branches:
      - main
      
jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - name: Checkout raganork-md repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install yarn dependencies
      run: yarn install --network-concurrency 1

    - name: Set environment variables
      run: |
        echo "SESSION_ID=${{ secrets.SESSION_ID }}" >> $GITHUB_ENV
        echo "OWNER_NAME=YourOwnerName" >> $GITHUB_ENV
        echo "ALWAYS_ONLINE=true" >> $GITHUB_ENV

    - name: Start raganork-md bot
      run: npm start

    # Optional: Add other steps as needed (e.g., testing, additional setup)

    # Optional: Post-deployment steps
    # ...

